import { model } from "@medusajs/framework/utils"

const Branch = model.define("restaurant_branch", {
  id: model.id().primaryKey(),
  name: model.text().searchable(),
  name_i18n_json: model.json().nullable(),
  slug: model.text().unique(),
  phone: model.text().nullable(),
  email: model.text().nullable(),
  address: model.text().nullable(),
  address_i18n_json: model.json().nullable(),
  pickup_instructions: model.text().nullable(),
  pickup_instructions_i18n_json: model.json().nullable(),
  latitude: model.number().nullable(),
  longitude: model.number().nullable(),
  image_url: model.text().nullable(),
  is_active: model.boolean().default(true),
  accepts_delivery: model.boolean().default(true),
  accepts_pickup: model.boolean().default(true),
  delivery_paused: model.boolean().default(false),
  pickup_paused: model.boolean().default(false),
  preparation_minutes: model.number().default(20),
  opening_hours_json: model.json().nullable(),
  timezone: model.text().default("Asia/Bahrain"),
  is_paused: model.boolean().default(false),
  pause_reason: model.text().nullable(),
  pause_until: model.dateTime().nullable(),
  prep_override_minutes: model.number().nullable(),
  prep_override_until: model.dateTime().nullable(),
  capacity_orders_per_hour: model.number().nullable(),
  scheduling_enabled: model.boolean().default(false),
  slot_minutes: model.number().default(15),
  max_orders_per_slot: model.number().nullable(),
  schedule_max_days: model.number().default(7),
})

export default Branch
